spring.application.name=appointment-api
server.port=8081
spring.mongodb.uri=mongodb+srv://hiruni0624_db_user:Hiruni123456@cluster0.x6ncgma.mongodb.net/medical_db?appName=Cluster0

notify.user-id=33111
notify.api-key=MPQsZcZN882ahNIl3tsG
notify.sender-id=NotifyDEMO
server.error.include-message=always
server.error.include-stacktrace=always
